# Generated by Django 3.2.21 on 2024-03-27 07:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("authors", models.CharField(max_length=200)),
                ("publication_date", models.DateField(blank=True, null=True)),
                ("ISBN", models.CharField(max_length=200)),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
        ),
    ]
